### ISSUE TITLE
Mining monero on my computer pls halpwkqq

### ISSUE THREAD

**Issue by Bansaidnes** [SemiConductorShortage/BadEngine#38]
Everytime i run this engine my CPU usage goes to 100% pls help how fix

**Comment by Bansaidnes** [comment]
Hello bedros pamboukian of year 10C in the winchester school Jebel ali.

**Comment by rxverse** [comment]
I complimented this engine over 35 times but now that I think about it, I do see my cpu and gpu usage up to 100% sometimes it goes above that mark but that's because I built my own gpu. I thought it just took a lot of resources but it can only make 2 pixels or so. Dear SemiConductorShortage or also known as Bedros Pamboukian of The Winchester School Jebel Ali in Year 10C please fix this issue asap or I will informing your computer science teacher ( Nisha Haris ) and your ICT teacher ( Reena Guglani) about this unaccpetable behaviour. Regards Rxverse (RIPWIN)

**Comment by SemiConductorShortage** [comment]
you doxxed me

**Comment by rxverse** [comment]
no? proof?
